name: Test on PR
'on': pull_request
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ secrets.ENV_FILE_CONTENT }}

jobs:
  # ios:
  #     runs-on: macos-latest
  #     steps:
  #       - name: Clone repository
  #         uses: actions/checkout@v4
  #       - name: Set up Flutter
  #         uses: subosito/flutter-action@v2
  #         with:
  #           channel: stable
  #           flutter-version-file: pubspec.yaml # path to pubspec.yaml
  #       - run: echo $env_var | base64 --decode > lib/src/core/utils/constants/env.dart
  #       - run: flutter pub get
  #       - run: flutter build ios --release --no-codesign
  # android:
  #     runs-on: macos-latest
  #     steps:
  #       - name: Clone repository
  #         uses: actions/checkout@v4
  #       - name: Set up Flutter
  #         uses: subosito/flutter-action@v2
  #         with:
  #           channel: stable
  #           flutter-version-file: pubspec.yaml # path to pubspec.yaml
  #       - run: echo $env_var | base64 --decode > lib/src/core/utils/constants/env.dart
  #       - run: flutter pub get
  #       - run: flutter build appbundle --release
  tests:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version-file: pubspec.yaml # path to pubspec.yaml
        - name: get a Env
          env:
            ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
          run: echo $ENV_FILE_CONTENT | base64 -d > lib/src/core/utils/constants/env.dart
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test --coverage
